# Generated by Django 6.0 on 2025-12-05 07:15

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogview',
            options={'ordering': ['-viewed_at'], 'verbose_name_plural': 'Blog Views'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blogview',
            name='viewed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(db_index=True, max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['title'], name='analytics_a_title_1a06b1_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['country', 'created_at'], name='analytics_a_country_3f33ab_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['author', 'country', 'created_at'], name='analytics_a_author__748b53_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['duration'], name='analytics_a_duratio_29cb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['country', 'viewed_at', 'blog'], name='analytics_a_country_cf4eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['user', 'viewed_at', 'blog'], name='analytics_a_user_id_1fe39c_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['blog', 'viewed_at', 'country'], name='analytics_a_blog_id_cca34c_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['viewed_at', 'country', 'user', 'blog'], name='analytics_a_viewed__3ffad9_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['country', 'viewed_at', 'user', 'blog'], name='analytics_a_country_2596a0_idx'),
        ),
    ]
